### ISSUE TITLE
NN optimization algorithm

### ISSUE THREAD

**Issue by pkomoro** [bbrozyna/light-propagation#9]
Implement NN optimization.

AC:
- use NNPropagation
- implement NN training

**Comment by pkomoro** [comment]
Done.

**Comment by micdol** [comment]
Where code? :D
You can, and actually should, tag either this issue in the commit message eg like "fixes #x" where x is issue number, or manually 
See https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
